### ISSUE TITLE
访问设备列表出错，这个是我姿势有问题吗？

### ISSUE THREAD

**Issue by mrhuo** [TripleView/MiHome.Net#3]
```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using MiHome.Net.Middleware;
using MiHome.Net.Service;

var hostBuilder = Host.CreateDefaultBuilder();
//添加小米米家的驱动服务，需要小米账号和密码
hostBuilder.ConfigureServices(it => it.AddMiHomeDriver(x =>
{
    x.UserName = "xxx";
    x.Password = "xxx";
}));
var host = hostBuilder.Build();
var miHomeDriver = host.Services.GetService<IMiHomeDriver>();
//列出家庭里所有的智能家居设备
var deviceList = await miHomeDriver?.Cloud?.GetDeviceListAsync();   // <---- 这里出错
Console.WriteLine(deviceList);
```
控制台信息：
```csharp
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.LogicalHandler[100]
      Start processing HTTP request GET https://account.xiaomi.com/pass/serviceLogin?sid=xiaomiio&_json=true
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.ClientHandler[100]
      Sending HTTP request GET https://account.xiaomi.com/pass/serviceLogin?sid=xiaomiio&_json=true
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.ClientHandler[101]
      Received HTTP response headers after 325.6286ms - 200
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.LogicalHandler[101]
      End processing HTTP request after 354.8538ms - 200
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.LogicalHandler[100]
      Start processing HTTP request POST https://account.xiaomi.com/pass/serviceLoginAuth2?_json=true
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.ClientHandler[100]
      Sending HTTP request POST https://account.xiaomi.com/pass/serviceLoginAuth2?_json=true
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.ClientHandler[101]
      Received HTTP response headers after 132.9929ms - 200
info: System.Net.Http.HttpClient.MiHome.Net.FeignService.IXiaoMiLoginService.LogicalHandler[101]
      End processing HTTP request after 138.56ms - 200
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at SummerBoot.Feign.DefaultFeignUnitOfWork.GetCookies(String url)
   at SummerBoot.Feign.FeignAspectSupport.ProcessCookie(RequestTemplate requestTemplate)
   at SummerBoot.Feign.FeignAspectSupport.BaseExecuteAsync[T](MethodInfo method, Object[] args, IServiceProvider serviceProvider)
   at SummerBoot.Feign.HttpService.ExecuteAsync[T](List`1 originArgs, MethodInfo method, IServiceProvider serviceProvider)
   at MiHome.Net.Service.MIotCloud.GetInternalLoginInfoAsync()
   at MiHome.Net.Service.MIotCloud.GetLoginInfoAsync()
   at MiHome.Net.Service.MIotCloud.BeginControlDeviceCookieAsync()
   at MiHome.Net.Service.MIotCloud.GetDeviceListAsync()
   at Program.<Main>$(String[] args) in G:\code\WpfApp1\MiHomeTest\Program.cs:line 16
   at Program.<Main>(String[] args)
``

**Comment by TripleView** [comment]
你好，添加一下我的wx,hezp666

**Comment by humoyun1798** [comment]
我也遇到了，好像是登录失败
![image](https://github.com/TripleView/MiHome.Net/assets/87974743/2827da95-612b-4675-8ad9-b1a05c82df2b)

**Comment by TripleView** [comment]
> 我也遇到了，好像是登录失败 ![image](https://private-user-images.githubusercontent.com/87974743/332000879-2827da95-612b-4675-8ad9-b1a05c82df2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzc5ODEsIm5iZiI6MTcxNjI3NzY4MSwicGF0aCI6Ii84Nzk3NDc0My8zMzIwMDA4NzktMjgyN2RhOTUtNjEyYi00Njc1LThhZDktYjFhMDVjODJkZjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA3NDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzlhMWVhNzBiMTk3NzhjZWI4Njc5MTEyMmI2NDM1MmRhYTE0YTc3OTBhNzUwMTAyMjhjNmY0OGI5YTc3MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-PnZxpHpM-FrgnRAHnsrm5ixSxzmTNRHHda48UWb2g8)

你好，你也添加一下我的微信，hezp666

**Comment by TripleView** [comment]
这个问题主要是登陆失败引起的，比如账号密码错误，或者账号需要到米家进行手机验证。
